services:
  postgres:
    image: postgres:16
    container_name: POST_MICRO
    environment:
      POSTGRES_DB: POST_MICRO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: